import {describe,it,expect} from 'vitest';
import {Session} from '../src/session.ts';
import {freshCampaign,deployment,levelInfo,award} from '../src/progression.ts';
import {trainingXp,expeditions,growthAdvice,expeditionReward,canExpedition} from '../src/expeditions.ts';
import {CONTROLLABLE,decide,key,manhattan,statsFor,type UnitClass} from '../../core/src/index.ts';
function play(s:Session){for(let i=0;i<900&&s.state.outcome==='ongoing';i++){
 const st=s.state;if(!CONTROLLABLE.has(st.currentSide)){s.tick();continue;}const u=st.living(st.currentSide).find(x=>!x.hasActed);if(!u){s.tick();continue;}
 if(u.hp<u.stats.maxHp*.5&&u.canUseItems&&s.medicine){s.act({kind:'item',unit:u.id,item:'medicine'});continue;}
 if(u.unitClass==='fengshui'&&u.mp>=8){const target=st.living().filter(t=>t.side!=='enemy'&&t.hp<t.stats.maxHp-20&&manhattan(t.pos,u.pos)<=3).sort((a,b)=>a.hp/a.stats.maxHp-b.hp/b.stats.maxHp)[0];if(target){s.act({kind:'item',unit:u.id,item:'heal',target:target.id});continue;}}
 if(u.id==='sima_yi'&&u.mp<5){const safe=[...st.map.reachable(u,st.occupancy()).keys()].map(k=>{const [x,y]=k.split(',').map(Number);return {x:x!,y:y!};}).filter(p=>st.living('enemy').every(e=>manhattan(p,e.pos)>e.range[1]+1)).sort((a,b)=>manhattan(a,u.pos)-manhattan(b,u.pos))[0];if(safe&&key(safe)!==key(u.pos))s.act({kind:'move',unit:u.id,to:safe});s.act({kind:'wait',unit:u.id});continue;}
 for(const cmd of decide(st,u)){if(cmd.kind==='move'&&key(cmd.to)===key(u.pos))continue;const r=s.act(cmd);expect(r.ok,r.error).toBe(true);if(st.outcome!=='ongoing')break;}if(!u.hasActed&&st.outcome==='ongoing')s.act({kind:'wait',unit:u.id});
}}

describe('growth balance',()=>{
 it('keeps the first eight story wins and treasure route within a modest training budget',()=>{const c=freshCampaign(),rows=[];for(let chapter=1;chapter<=8;chapter++){award(c,'S1-0'+chapter,'normal',['sima_yi','cao_zhen'],[1]);for(const q of expeditions.filter(m=>m.kind==='quest'&&m.requires===chapter)){let wins=0;while(levelInfo(c.xp.sima_yi!).level<q.level&&wins<30){const current=levelInfo(c.xp.sima_yi!).level;const t=expeditions.filter(m=>m.kind==='training'&&canExpedition(c,m.id)&&m.level<=current+1).at(-1)!;expeditionReward(c,t.id,q.id+'-'+wins++,true);}rows.push({quest:q.id,training:wins,level:levelInfo(c.xp.sima_yi!).level});expect(wins).toBeLessThanOrEqual(5);const before=c.xp.sima_yi!;expect(expeditionReward(c,q.id,q.id,true).xp).toBe(100+q.level*12);expect(expeditionReward(c,q.id,q.id+'-again',true).xp).toBe(0);expect(c.xp.sima_yi).toBe(before+100+q.level*12);}}console.log('GROWTH_ROUTE',JSON.stringify(rows));});
 it('reduces overlevel rewards gradually instead of a cliff',()=>{const c=freshCampaign(),m=expeditions[1]!;let last=trainingXp(c,m);for(let xp=0;xp<8000;xp+=50){c.xp.sima_yi=xp;const next=trainingXp(c,m);expect(next).toBeLessThanOrEqual(last);expect(last-next).toBeLessThanOrEqual(12);expect(next).toBeGreaterThanOrEqual(26);last=next;}});
 it('estimates training using the actual diminishing reward',()=>{const c=freshCampaign();expect(growthAdvice(c,2)).toContain('약 2승');expeditionReward(c,'T01','a',true);expeditionReward(c,'T01','b',true);expect(levelInfo(c.xp.sima_yi!).level).toBe(2);expect(growthAdvice(c,2)).toContain('충족');});
 it('caps support levels only for newly balanced deployments',()=>{const d=deployment(freshCampaign(),true);d.mission={id:'T06',runId:'cap',version:3,balance:1};const s=new Session(7,'normal',215,'survival',4,d);expect(s.state.living('ally').every(u=>u.level<=2)).toBe(true);delete d.mission.balance;const old=new Session(7,'normal',215,'survival',4,d);expect(old.state.living('ally').some(u=>u.level===27)).toBe(true);});
 it('scales spawned defense enemies once and preserves save replay',()=>{const d=deployment(freshCampaign(),true);d.levels.sima_yi=8;d.levels.cao_zhen=8;d.mission={id:'T03',runId:'wave',version:3,balance:1};const s=new Session(7,'normal',215,'survival',4,d);for(let i=0;i<50&&!s.state.find('trial_wave_3')&&s.state.outcome==='ongoing';i++){if(CONTROLLABLE.has(s.state.currentSide))s.act({kind:'endPhase'});else s.tick();}const wave=s.state.find('trial_wave_3');expect(wave).toBeDefined();expect(wave!.stats.attack).toBe(Math.round(statsFor('infantry',8).attack*.6));expect(Session.load(s.save()).state.snapshot()).toEqual(s.state.snapshot());});
 it('clears introductory training with three practical support combinations',()=>{const rows=[];for(const support of [['infantry','fengshui'],['archer','fengshui'],['spearman','maiden']] as UnitClass[][])for(const seed of [215,216,217]){const d=deployment(freshCampaign(),true);d.mission={id:'T01',runId:'play',version:4,balance:1,supportClasses:support};const s=new Session(7,'normal',seed,'survival',4,d);play(s);rows.push({support:support.join('+'),seed,outcome:s.state.outcome,turn:s.state.turn});}console.log('BALANCE_PLAY',JSON.stringify(rows));expect(rows.filter(r=>r.outcome==='victory').length).toBe(9);});
});
