import {describe,it,expect} from 'vitest';
import {Session} from '../src/session.ts';
import {deployment,freshCampaign} from '../src/progression.ts';
import {trialGoals} from '../src/expedition-objectives.ts';
import {expeditions} from '../src/expeditions.ts';
import {evaluateGroup,decide,runEvents} from '../../core/src/index.ts';
function trial(id:string,version:2|3|4=4){const d=deployment(freshCampaign(),true);d.mission={id,runId:'objectives-'+id,version,supportClasses:['infantry','fengshui']};return new Session(7,'normal',215,'survival',4,d);}
describe('distinct expedition objectives',()=>{
 it.each(expeditions.map(m=>m.id))('%s loads with a versioned objective and replays',id=>{const s=trial(id);expect(s.state.outcome).toBe('ongoing');expect(s.state.scenarioPhase).toBe(trialGoals[id]!.name);expect(Session.load(s.save()).state.snapshot()).toEqual(s.state.snapshot());for(const u of s.state.living().filter(u=>!u.id.startsWith('tower_')&&!u.id.startsWith('gate_')))expect(s.state.map.moveCost(u.unitClass,u.pos)).toBeLessThan(Infinity);});
 it('preserves old annihilation saves',()=>{expect(trial('T02',2).state.victory[0]!.type).toBe('annihilate');expect(trial('T02').state.victory[0]!.type).toBe('reach');});
 it('escort requires the convoy to reach its exit even if every enemy is gone',()=>{const s=trial('Q01'),v=s.state.get('convoy_trial');for(const u of s.state.living('enemy'))s.state.retreat(u);expect(evaluateGroup(s.state,s.state.victory)).toBe(false);v.pos={...s.state.map.regionCoords('trial_goal')[0]!};expect(evaluateGroup(s.state,s.state.victory)).toBe(true);s.state.retreat(v);expect(evaluateGroup(s.state,s.state.defeat)).toBe(true);});
 it('rescues by adjacency then requires return to safety',()=>{const s=trial('Q03'),v=s.state.get('rescue_target'),hero=s.state.get('sima_yi');expect(v.side).toBe('enemy');hero.pos={x:v.pos.x-1,y:v.pos.y};expect(s.act({kind:'wait',unit:hero.id}).ok).toBe(true);expect(v.side).toBe('ally');expect(evaluateGroup(s.state,s.state.victory)).toBe(false);v.pos={...s.state.map.regionCoords('trial_safe')[0]!};expect(evaluateGroup(s.state,s.state.victory)).toBe(true);});
 it('capture needs an actual capture command, not enemy annihilation',()=>{const s=trial('Q02'),hero=s.state.get('sima_yi');hero.pos={...s.state.map.regionCoords('trial_goal')[0]!};expect(evaluateGroup(s.state,s.state.victory)).toBe(false);expect(s.act({kind:'capture',unit:hero.id,region:'trial_goal'}).ok).toBe(true);expect(s.state.outcome).toBe('victory');expect(s.state.living('enemy').length).toBeGreaterThan(0);});
 it('defense waits full rounds and fails on any goal breach',()=>{const s=trial('T03');s.state.turn=5;expect(evaluateGroup(s.state,s.state.victory)).toBe(false);s.state.turn=6;expect(evaluateGroup(s.state,s.state.victory)).toBe(true);const enemy=s.state.get('trial_enemy_0');enemy.pos={...s.state.map.regionCoords('trial_defense')[0]!};expect(evaluateGroup(s.state,s.state.defeat)).toBe(true);});
 it('spawns defense reinforcements once and attacks occupied defensive goals',()=>{const s=trial('T03');s.state.turn=3;runEvents(s.state,{kind:'turn_start',side:'enemy'});expect(s.state.find('trial_wave_3')).toBeDefined();runEvents(s.state,{kind:'turn_start',side:'enemy'});expect(s.state.living().filter(u=>u.id==='trial_wave_3')).toHaveLength(1);const goals=s.state.map.regionCoords('trial_defense');s.state.get('sima_yi').pos={...goals[0]!};s.state.get('cao_zhen').pos={...goals[1]!};const e=s.state.get('trial_enemy_0');e.pos={x:4,y:4};expect(decide(s.state,e).some(c=>c.kind==='attack')).toBe(true);});
});
