import {describe,it,expect} from 'vitest';
import {Session,campaignOrder} from '../src/session.ts';
import {freshCampaign,deployment,award} from '../src/progression.ts';
import {CONTROLLABLE,decide,key,manhattan} from '../../core/src/index.ts';
function create(difficulty:'normal'|'extreme'='normal',seed=215){const c=freshCampaign();c.xp.sima_yi=560;return new Session(5,difficulty,seed,difficulty==='extreme'?'strategy':'survival',3,deployment(c));}
function play(s:Session){for(let i=0;i<800&&s.state.outcome==='ongoing';i++){
 if(CONTROLLABLE.has(s.state.currentSide)){const u=s.state.living(s.state.currentSide).find(u=>!u.hasActed);if(u?.canUseItems&&u.hp<u.stats.maxHp*.65&&s.medicine>0){s.act({kind:'item',unit:u.id,item:'medicine'});continue;}if(!u)s.tick();else if(u.hasMoved)s.act({kind:'wait',unit:u.id});else{for(const cmd of decide(s.state,u)){if(cmd.kind==='move'&&key(cmd.to)===key(u.pos))continue;const r=s.act(cmd);expect(r.ok,r.error).toBe(true);if(s.state.outcome!=='ongoing')break;}if(s.state.outcome==='ongoing'&&!u.hasActed)s.act({kind:'wait',unit:u.id});}}else s.tick();
}}
describe('장강 퇴각전',()=>{
 it.each(['bridge','shore'])('clears the new rules escort route %s',route=>{const prior=create(),s=new Session(5,'normal',215,'survival',4,prior.deployment);s.act({kind:'choose',nodeId:'retreat_route',optionId:route});play(s);expect(s.state.outcome,s.failure).toBe('victory');expect(Session.load(s.save()).state.snapshot()).toEqual(s.state.snapshot());});
 it.each(['normal','extreme'] as const)('completes both escort routes with replay on %s',difficulty=>{
  // 최상: 시험 봇(사람보다 서툰 기본 AI)은 시드 20개 기준 3할쯤 이긴다(기병 팔방 공격 전 4할). 시드 하나에 운을 걸지 않고 둘 중 하나로 본다.
  for(const route of ['bridge','shore']){const run=(seed:number)=>{const s=create(difficulty,seed);expect(s.act({kind:'choose',nodeId:'retreat_route',optionId:route}).ok).toBe(true);play(s);return s;};let s=run(215);if(difficulty==='extreme'&&s.state.outcome!=='victory')s=run(5);expect(s.state.outcome,JSON.stringify({difficulty,route,turn:s.state.turn,failure:s.failure,convoys:s.state.living('allyAi').map(u=>({hp:u.hp,pos:u.pos})),log:s.state.log.slice(-4)})).toBe('victory');expect(s.seals).toContain(1);if(route==='shore')expect(s.state.log.some(e=>e.t==='move'&&e.unit.startsWith('convoy_')&&e.to.y===14&&e.to.x>=10&&e.to.x<=14)).toBe(true);expect(Session.load(JSON.parse(JSON.stringify(s.save()))).state.snapshot()).toEqual(s.state.snapshot());expect(s.undo()).toBe(true);expect(s.state.outcome).toBe('ongoing');}
 });
 it('restores route choice and convoy destination on undo',()=>{const s=create();expect(s.tick()).toBe(false);s.act({kind:'choose',nodeId:'retreat_route',optionId:'shore'});expect(s.state.get('convoy_a').goalRegion).toBe('south_approach');const restored=Session.load(s.save());expect(restored.phase).toBe('남쪽 강변 호위');expect(restored.undo()).toBe(true);expect(restored.state.activeDialogue).toBe('retreat_route');expect(restored.state.get('convoy_a').goalRegion).toBe('escort_goal');});
 it('permits one convoy loss but fails when both are lost',()=>{const s=create();s.act({kind:'choose',nodeId:'retreat_route',optionId:'bridge'});s.state.retreat(s.state.get('convoy_a'));s.act({kind:'wait',unit:'sima_yi'});expect(s.state.outcome).toBe('ongoing');s.state.retreat(s.state.get('convoy_b'));s.act({kind:'wait',unit:'cao_zhen'});expect(s.state.outcome).toBe('defeat');expect(s.failure).toContain('두 부대');expect(s.seals).toEqual([]);});
 it('wins on one convoy arrival while enemies remain and does not require both alive',()=>{const s=create();s.act({kind:'choose',nodeId:'retreat_route',optionId:'bridge'});s.state.retreat(s.state.get('convoy_a'));s.state.get('convoy_b').pos={x:22,y:10};s.act({kind:'wait',unit:'sima_yi'});expect(s.state.outcome).toBe('victory');expect(s.state.living('enemy').length).toBeGreaterThan(0);expect(s.seals).not.toContain(2);});
 it('keeps convoys unarmed and uncontrolled, and rewards the new story once',()=>{const s=create();expect(s.state.map.width).toBe(24);expect(s.state.map.height).toBe(18);expect(s.state.get('convoy_a').stats.movement).toBe(3);expect(s.state.get('convoy_a').range).toEqual([0,0]);s.act({kind:'choose',nodeId:'retreat_route',optionId:'bridge'});expect(s.act({kind:'move',unit:'convoy_a',to:{x:3,y:9}}).ok).toBe(false);expect(campaignOrder.indexOf(5)).toBe(campaignOrder.indexOf(4)+1);const c=freshCampaign();expect(award(c,'S1-05','normal',[],[1]).treasure?.id).toBe('dunjia');expect(award(c,'S1-05','normal',[],[1]).xp).toBe(0);});
});
