import {storyBeats,stories} from '../src/story.ts';
import {describe,it,expect} from 'vitest';
import {Session,campaignOrder,chapters} from '../src/session.ts';
import {freshCampaign,deployment,award,equip} from '../src/progression.ts';
import {CONTROLLABLE,decide,key,manhattan} from '../../core/src/index.ts';
function create(difficulty:'normal'|'extreme'='normal',preparation:'strategy'|'survival'='strategy'){
 const c=freshCampaign();for(const index of [2,0,3,4,5])award(c,chapters[index]!.stage.id,'normal',chapters[index]!.stage.deployment.forced,[1]);if(difficulty==='extreme')award(c,'S1-06','normal',['sima_yi','cao_zhen'],[1]);equip(c,'sima_yi','mengde');equip(c,'cao_zhen',difficulty==='extreme'?'yitian':'sevenstar');return new Session(6,difficulty,215,preparation,3,deployment(c));
}
function play(s:Session,guardId:string){for(let i=0;i<1800&&s.state.outcome==='ongoing';i++){
 const st=s.state;if(!CONTROLLABLE.has(st.currentSide)){s.tick();continue;}const u=st.living(st.currentSide).find(u=>!u.hasActed);if(!u){s.tick();continue;}
 if(u.unitClass==='fengshui'&&u.mp>=8){const target=st.living().filter(t=>t.side!=='enemy'&&t.hp<t.stats.maxHp-20&&manhattan(t.pos,u.pos)<=3).sort((a,b)=>a.hp/a.stats.maxHp-b.hp/b.stats.maxHp)[0];if(target){const cmd={kind:'item',unit:u.id,item:'heal',target:target.id} as const;expect(s.act(cmd).ok).toBe(true);const restored=Session.load(s.save());expect(restored.state.snapshot()).toEqual(s.state.snapshot());expect(restored.undo()).toBe(true);expect(restored.act(cmd).ok).toBe(true);expect(restored.state.snapshot()).toEqual(s.state.snapshot());continue;}}
 if(u.canUseItems&&u.hp<u.stats.maxHp*.5&&s.medicine>0){s.act({kind:'item',unit:u.id,item:'medicine'});continue;}
 if(u.id===guardId){if(guardId!=='xu_chu'&&!u.hasMoved&&manhattan(u.pos,st.get('cao_cao').pos)>1){const to={x:4,y:10};expect(s.act({kind:'move',unit:u.id,to}).ok).toBe(true);}const adjacent=st.living('enemy').find(e=>manhattan(u.pos,e.pos)===1);s.act(adjacent?{kind:'attack',unit:u.id,target:adjacent.id}:{kind:'wait',unit:u.id});continue;}
 if(u.unitClass==='catapult'&&st.find('gate_21_10')?.alive){const gate=st.get('gate_21_10');if(!u.hasMoved){const at={x:17,y:10};if(st.map.reachable(u,st.occupancy()).has(key(at))&&key(at)!==key(u.pos))s.act({kind:'move',unit:u.id,to:at});}if(manhattan(u.pos,gate.pos)>=2&&manhattan(u.pos,gate.pos)<=4)s.act({kind:'attack',unit:u.id,target:gate.id});else for(const cmd of decide(st,u)){if(cmd.kind!=='capture'&&!(cmd.kind==='move'&&key(cmd.to)===key(u.pos)))s.act(cmd);}if(!u.hasActed)s.act({kind:'wait',unit:u.id});continue;}
 if(u.id==='sima_yi'&&!st.find('ma_chao')?.alive&&!st.find('gate_21_10')?.alive){if(st.map.regionCoords('breakthrough').some(p=>key(p)===key(u.pos))){s.act({kind:'capture',unit:u.id,region:'breakthrough'});continue;}if(!u.hasMoved){const goal=u.pos.x<22?{x:22,y:10}:{x:24,y:10};const cells=[...st.map.reachable(u,st.occupancy()).keys()].map(k=>{const [x,y]=k.split(',').map(Number);return {x:x!,y:y!};}).filter(p=>key(p)!==key(u.pos)).sort((a,b)=>manhattan(a,goal)-manhattan(b,goal));if(cells[0])s.act({kind:'move',unit:u.id,to:cells[0]});}if(st.map.regionCoords('breakthrough').some(p=>key(p)===key(u.pos)))s.act({kind:'capture',unit:u.id,region:'breakthrough'});else s.act({kind:'wait',unit:u.id});continue;}
 if(u.id==='sima_yi'&&st.find('ma_chao')?.alive){
   const boss=st.get('ma_chao');if(manhattan(u.pos,boss.pos)<=4&&u.mp>=9){s.act({kind:'strategy',unit:u.id,strategy:'windDragon',at:boss.pos});continue;}
   if(!u.hasMoved){const goal=u.mp>=9?{x:20,y:8}:{x:8,y:9};const cells=[...st.map.reachable(u,st.occupancy()).keys()].map(k=>{const [x,y]=k.split(',').map(Number);return {x:x!,y:y!};}).filter(p=>key(p)!==key(u.pos)).sort((a,b)=>manhattan(a,goal)-manhattan(b,goal));if(cells[0])s.act({kind:'move',unit:u.id,to:cells[0]});}
   s.act({kind:'wait',unit:u.id});continue;
 }
 if(u.hasMoved){s.act({kind:'wait',unit:u.id});continue;}
 const view=Object.create(st);if(st.find('ma_chao')?.alive)view.victory=st.victory.filter(v=>v.type!=='capture');
 for(const cmd of decide(view,u)){if(cmd.kind==='move'&&key(cmd.to)===key(u.pos))continue;const r=s.act(cmd);expect(r.ok,r.error).toBe(true);if(st.outcome!=='ongoing')break;}
 if(!u.hasActed&&st.outcome==='ongoing')s.act({kind:'wait',unit:u.id});
}}
describe('동관 · 두 전선',()=>{
 it.each(['normal','extreme'] as const)('clears revision 4 with the mandatory ram and officer traits on %s',difficulty=>{const prior=create(difficulty),s=new Session(6,difficulty,215,'strategy',4,prior.deployment);expect(s.act({kind:'choose',nodeId:'tongguan_plan',optionId:'rear'}).ok).toBe(true);expect(s.state.get('xu_chu').traits).toContain('guardian');play(s,'xu_chu');expect(s.state.outcome,JSON.stringify({turn:s.state.turn,failure:s.failure})).toBe('victory');expect(Session.load(s.save()).state.snapshot()).toEqual(s.state.snapshot());});
 it.each([['normal','rear'],['normal','front'],['extreme','rear'],['extreme','front']] as const)('protects Cao Cao and captures the pass on %s/%s',(difficulty,route)=>{
 const s=create(difficulty,route==='front'?'survival':'strategy');s.act({kind:'choose',nodeId:'tongguan_plan',optionId:route});play(s,route==='rear'?'xu_chu':'granted_infantry_0');expect(s.state.outcome,JSON.stringify({turn:s.state.turn,failure:s.failure,hero:s.state.get('sima_yi').hp,pos:s.state.get('sima_yi').pos,gate:s.state.get('gate_21_10').hp,captured:[...s.state.captured],cao:s.state.get('cao_cao').hp,boss:s.state.get('ma_chao').hp,log:s.state.log.slice(-6)})).toBe('victory');expect(s.state.find('cao_cao')?.alive).toBe(true);expect(s.state.captured.get('breakthrough')).toBe('player');expect(Session.load(s.save()).state.snapshot()).toEqual(s.state.snapshot());expect(s.undo()).toBe(true);expect(s.state.outcome).toBe('ongoing');
 });
 it('changes Xu Chu deployment without duplicating him and restores the choice',()=>{const s=create();s.act({kind:'choose',nodeId:'tongguan_plan',optionId:'front'});expect(s.state.get('xu_chu').pos).toEqual({x:10,y:10});const restored=Session.load(s.save());restored.undo();expect(restored.state.find('xu_chu')).toBeUndefined();restored.act({kind:'choose',nodeId:'tongguan_plan',optionId:'rear'});expect(restored.state.get('xu_chu').pos).toEqual({x:4,y:12});});
 it('rejects premature capture and loses when the protected commander retreats',()=>{const s=create();s.act({kind:'choose',nodeId:'tongguan_plan',optionId:'rear'});s.state.get('sima_yi').pos={x:24,y:10};expect(s.act({kind:'capture',unit:'sima_yi',region:'breakthrough'}).ok).toBe(false);s.state.retreat(s.state.get('cao_cao'));s.act({kind:'wait',unit:'sima_yi'});expect(s.state.outcome).toBe('defeat');expect(s.failure).toContain('조조');});
 it('makes healing consume MP and the action, validates range and cannot revive',()=>{const s=create();s.act({kind:'choose',nodeId:'tongguan_plan',optionId:'rear'});s.act({kind:'endPhase'});const healer=s.state.get('granted_fengshui_0'),target=s.state.get('granted_infantry_0');target.hp-=20;const before=healer.mp;expect(s.act({kind:'item',unit:healer.id,item:'heal',target:target.id}).ok).toBe(true);expect(target.hp).toBe(target.stats.maxHp);expect(healer.mp).toBe(before-8);expect(healer.hasActed).toBe(true);expect(s.act({kind:'item',unit:healer.id,item:'heal',target:target.id}).ok).toBe(false);});
 it('rejects invalid healing targets without spending MP or an action',()=>{const s=create();s.act({kind:'choose',nodeId:'tongguan_plan',optionId:'rear'});s.act({kind:'endPhase'});const u=s.state.get('granted_fengshui_0'),t=s.state.get('granted_infantry_0'),mp=u.mp;
  for(const id of [t.id,'ma_chao','missing'])expect(s.act({kind:'item',unit:u.id,item:'heal',target:id}).ok).toBe(false);
  t.hp-=10;t.pos={x:27,y:19};expect(s.act({kind:'item',unit:u.id,item:'heal',target:t.id}).ok).toBe(false);t.pos={...u.pos};s.state.retreat(t);expect(s.act({kind:'item',unit:u.id,item:'heal',target:t.id}).ok).toBe(false);expect(u.mp).toBe(mp);expect(u.hasActed).toBe(false);
 });
 it('provides a complete story entry for every playable chapter',()=>{chapters.forEach((c,i)=>{expect(storyBeats[c.stage.id]?.length).toBeGreaterThanOrEqual(3);expect(stories[i]?.length).toBe(2);});});
 it('has a distinct medium-size fortress and persistent campaign position',()=>{const s=create();expect([s.state.map.width,s.state.map.height]).toEqual([28,20]);expect(s.state.get('gate_21_10').hp).toBe(95);expect(s.state.get('tower_21_6').stats.movement).toBe(0);expect(campaignOrder.indexOf(6)).toBe(campaignOrder.indexOf(5)+1);});
});
