import {describe,it,expect} from 'vitest';
import {treasures,treasureInfo,applyTreasure,treasurePowerText,freshCampaign,deployment} from '../src/progression.ts';
import {treasurePowers,makeUnit,createDamageContext,applyTraitHooks,getTrait,estimatePhysical,estimateStrategy,ignoresRough,counterLimitOf} from '../../core/src/index.ts';
import {Session} from '../src/session.ts';
function unit(){return makeUnit({id:'a',unitClass:'infantry',level:10,side:'player',pos:{x:1,y:1}});}
describe('individual treasure powers',()=>{
 it('covers every treasure with a registered effect; the first 60 have distinct atlas cells',()=>{expect(treasurePowers).toHaveLength(treasures.length);expect(new Set(treasures.map(t=>treasureInfo(t.id).icon).filter(i=>i>=0)).size).toBe(60);expect(treasures.filter(t=>treasureInfo(t.id).icon<0)).toHaveLength(treasures.length-60);for(const t of treasures){const u=unit();applyTreasure(u,t.id);expect(u.traits).toContain('treasure:'+t.id);expect(getTrait('treasure:'+t.id).description).toBe(treasurePowerText(t.id));expect(treasurePowerText(t.id).length).toBeGreaterThan(5);}});
 it('applies conditional movement effects only after a real move',()=>{const a=unit(),d=unit();applyTreasure(a,'dragonSpear');a.hasMoved=true;a.hasActed=true;let ctx=createDamageContext(a,d,'physical');applyTraitHooks(ctx);expect(ctx.suppressCounter).toBe(false);a.movedThisTurn=true;ctx=createDamageContext(a,d,'physical');applyTraitHooks(ctx);expect(ctx.suppressCounter).toBe(true);});
 it('gives rattan armor a real physical benefit and strategy drawback',()=>{const a=unit(),d=unit();applyTreasure(d,'rattanArmor');let ctx=createDamageContext(a,d,'physical');applyTraitHooks(ctx);expect(ctx.reduction).toBeCloseTo(.18);ctx=createDamageContext(a,d,'strategy');applyTraitHooks(ctx);expect(ctx.reduction).toBeCloseTo(-.12);});
 it('caps recovery, limits counters and supports rough terrain traversal',()=>{const u=unit();applyTreasure(u,'qingshu');u.hp=u.stats.maxHp-3;getTrait('treasure:qingshu').hooks.onTurnStart!(u,0);expect(u.hp).toBe(u.stats.maxHp);applyTreasure(u,'threeStrategies');u.mp=0;getTrait('treasure:threeStrategies').hooks.onTurnStart!(u,0);expect(u.mp).toBe(3);applyTreasure(u,'dunjia');expect(ignoresRough(u)).toBe(true);applyTreasure(u,'twinHalberds');expect(counterLimitOf(u)).toBe(2);});
 it('changes real damage estimates and preserves legacy equipment rules',()=>{const c=freshCampaign();c.equipped.cao_zhen='qinggang';const modern=deployment(c,true);modern.mission={id:'T01',runId:'gear',version:3};const s=new Session(7,'normal',215,'survival',4,modern),a=s.state.get('cao_zhen'),d=s.state.get('trial_enemy_0');const withGear=estimatePhysical(a,d,s.state.map);a.traits=a.traits.filter(t=>t!=='treasure:qinggang');expect(estimatePhysical(a,d,s.state.map)).toBeLessThan(withGear);delete modern.treasureRules;const old=new Session(7,'normal',215,'survival',4,modern);expect(old.state.get('cao_zhen').traits).not.toContain('treasure:qinggang');expect(Session.load(old.save()).state.snapshot()).toEqual(old.state.snapshot());});
 it('suppresses counters in actual combat only after moving',()=>{for(const moved of [false,true]){const d=deployment(freshCampaign(),true);d.equipped.cao_zhen='dragonSpear';d.mission={id:'T01',runId:'counter',version:3};const s=new Session(7,'normal',215,'survival',4,d),a=s.state.get('cao_zhen'),e=s.state.get('trial_enemy_0');a.pos={x:moved?6:7,y:4};e.pos={x:8,y:4};e.hp=1000;if(moved)expect(s.act({kind:'move',unit:a.id,to:{x:7,y:4}}).ok).toBe(true);expect(s.act({kind:'attack',unit:a.id,target:e.id}).ok).toBe(true);expect(s.state.log.some(l=>l.t==='counter')).toBe(!moved);}});
 it('replays modern equipped turn recovery without duplicating traits',()=>{const c=freshCampaign();c.equipped.sima_yi='threeStrategies';const d=deployment(c,true);d.mission={id:'T01',runId:'replay',version:3};const s=new Session(7,'normal',215,'survival',4,d);s.act({kind:'endPhase'});s.act({kind:'endPhase'});for(let i=0;i<12&&s.state.currentSide!=='player';i++)s.tick();expect(Session.load(s.save()).state.snapshot()).toEqual(s.state.snapshot());expect(s.state.get('sima_yi').traits.filter(t=>t==='treasure:threeStrategies')).toHaveLength(1);});
});
