import {troopAdvice} from './troop-tactics.ts';
import {troopRoles} from './troops.ts';
import {expeditions,canExpedition,storyWins} from './expeditions.ts';
import type {Unit} from '../../core/src/index.ts';
import {treasures,treasurePowerText,treasureInfo,gearNames,equippedItems,deployment,gearKey,type Campaign,type GearSlot} from './progression.ts';
import {officerFeatures,allStrategies,strategyHint,talentTree,martialPower} from './officers.ts';
import {classNames,unitName} from './battlefield.ts';
import {RELICS} from './roguelike.ts';
import {specialOf} from './treasure-specials.ts';
import {romanceOf} from './romance.ts';
export {treasureIcon} from './treasure-art.ts';
import {treasureIcon} from './treasure-art.ts';
export function campMarkup(c:Campaign,units:Unit[],selected:string,filter:string,inspect:string,portrait:(u:Unit)=>string,relics:string[]=[],forced:readonly string[]=[]){
 const u=units.find(x=>gearKey(x)===selected)??units[0]!,feature=officerFeatures[u.id],owned=equippedItems(c,gearKey(u)),item=treasures.find(t=>t.id===inspect&&c.treasures.includes(t.id));
 // 보물 도감은 가진 보물만 보인다(못 얻은 보물은 목록에도 나오지 않는다).
 const slotNow:GearSlot=(filter in gearNames?filter:'weapon') as GearSlot;
 const mine=treasures.filter(t=>c.treasures.includes(t.id)&&treasureInfo(t.id).slot===slotNow);
 const holder=(id:string)=>units.find(x=>gearKey(x)!==gearKey(u)&&equippedItems(c,gearKey(x)).includes(id));
 return `<div class="camp-workbench"><section class="camp-roster"><div class="section-label">출진 부대 <span>${units.length}명 · 시나리오 편성</span></div><div class="officer-grid">${units.map(x=>`<button data-officer="${gearKey(x)}" class="officer-card ${x.id===u.id?'chosen':''}">${portrait(x)}<strong>${unitName(x)}</strong><small>Lv.${x.level} · ${classNames[x.unitClass]}</small><em>${x.unitClass==='ram'?'공성 필수':x.side==='player'?(forced.length&&!forced.includes(x.id)?'본대':'본대 필수'):'지원 부대'}</em></button>`).join('')}</div><p class="muted">장수를 선택해 능력·보물·고유특성을 정비하세요. 필수 장수와 공성대는 제외할 수 없습니다.</p></section>
 <section class="camp-detail"><div class="section-label">부대 정보 <span>${classNames[u.unitClass]}</span></div><div class="camp-hero">${portrait(u)}<div><h3>${unitName(u)}</h3><p>Lv.${u.level} · ${(r=>r?`무력 ${r.war} · 지력 ${r.int}`:`무력 ${martialPower(u)}`)(romanceOf(u))}</p><p>HP ${u.hp} / MP ${u.mp}</p></div></div><div class="camp-stats">${[['공격',u.stats.attack],['방어',u.stats.defense],['책략력',u.stats.intellect],['정신',u.stats.spirit],['민첩',u.stats.agility],['이동',u.stats.movement]].map(([k,v])=>`<span>${k}<b>${v}</b></span>`).join('')}</div><div class="troop-tactic-card"><b>병종 운용 · 사거리 ${u.range[0]===u.range[1]?u.range[0]:`${u.range[0]}~${u.range[1]}`}</b><p>${troopAdvice[u.unitClass]}</p></div><h4>장수 고유특성 · 성장의 증표</h4>${feature?talentTree(u.id,u.level,deployment(c,true).growth!).map(t=>`<p class="feature-card ${t.ready?'':'locked'}"><b>${t.ready?'◆':'◇'} ${t.name}</b> · ${t.ready?'해금':'잠김'}<br>${t.description}<br><small>${t.requirement}</small></p>`).join(''):`<p class="feature-card">${troopRoles[u.unitClass]?.role??(u.unitClass==='ram'?'공성 충격 · 구조물 피해 3배':'병종 전문화 · 이동/사거리/지형 상성')}</p>`}<div class="gear-slots">${(Object.keys(gearNames) as GearSlot[]).map(slot=>{const id=owned.find(id=>treasureInfo(id).slot===slot);return `<div class="${filter===slot?'on':''}" data-gear-filter="${slot}"><small>${gearNames[slot]}</small>${id?treasureIcon(id):'<i class="empty-slot">＋</i>'}<span>${treasures.find(t=>t.id===id)?.name??'미장착'}</span>${id?`<button data-unequip="${slot}">해제</button>`:''}</div>`;}).join('')}</div></section></div>
 <section class="treasury">${relics.length?`<div class="section-label">회차 보물 <span>${relics.length}점 · 출진한 부대 전원에 저절로 적용</span></div><div class="run-relic-strip">${relics.map(id=>RELICS.find(r=>r.id===id)).filter(Boolean).map(r=>`<span class="run-relic-card"><b>${r!.name}</b><small>${r!.effect}</small></span>`).join('')}</div>`:''}<div class="section-label">보물 <span>보유 ${c.treasures.length}점 · 부위별 1점</span></div><div class="treasury-filters">${Object.entries(gearNames).map(([id,name])=>`<button data-gear-filter="${id}" class="${slotNow===id?'active':''}">${name} <small>${treasures.filter(t=>c.treasures.includes(t.id)&&treasureInfo(t.id).slot===id).length}</small></button>`).join('')}<span class="muted">${unitName(u)}에게 장착할 ${gearNames[slotNow]}</span></div><div class="treasury-body"><div class="treasure-grid">${mine.length?mine.map(t=>{const m=treasureInfo(t.id);const on=owned.includes(t.id),h=holder(t.id);return `<div class="treasure-tile grade-${m.grade} ${t.id===inspect?'chosen':''} ${on?'worn':''}"><button class="tt-pick" data-treasure="${t.id}" aria-label="${t.name} · ${m.rarity}">${treasureIcon(t.id)}<strong>${t.name}</strong><small>${'★'.repeat(m.grade)} · ${t.effect}</small>${specialOf(t.id)?`<em class="tt-special">✦ ${specialOf(t.id)!.name}</em>`:''}</button>${on?`<button data-unequip="${slotNow}" class="tt-act on">장착 중 · 해제</button>`:`<button data-equip-id="${t.id}" class="tt-act" ${u.side==='player'?'':'disabled'}>${h?`${unitName(h)}에게서 옮겨 장착`:'장착'}</button>`}</div>`;}).join(''):`<p class="treasure-empty">${'아직 가진 '+gearNames[slotNow]+'가 없습니다.'}<br><small>본편 전장의 첫 승리와 보물 인연 외전에서 얻습니다.</small></p>`}</div><div class="treasure-description">${item?`${treasureIcon(item.id)}<h3>${item.name}</h3><p>${treasureInfo(item.id).rarity} · ${gearNames[treasureInfo(item.id).slot]}</p><p>${item.effect}</p><p class="treasure-unique"><b>고유 효과</b><br>${treasurePowerText(item.id)}</p>${specialOf(item.id)?`<p class="treasure-special"><b>✦ 특기 「${specialOf(item.id)!.name}」</b><br>${specialOf(item.id)!.text}</p>`:''}<small>${item.description}</small><p>입수: ${item.quest?(expeditions.find(m=>m.id===item.quest)?.name??item.quest)+' · '+(canExpedition(c,item.quest)?'도전 가능':'본편 '+(expeditions.find(m=>m.id===item.quest)?.requires??0)+'승 필요 · 현재 '+storyWins(c)+'승'):item.stage+' 첫 승리'}</p><button id="equip-treasure" ${c.treasures.includes(item.id)&&u.side==='player'?'':'disabled'}>${unitName(u)}에게 장착</button>`:'보물을 선택하면 효과와 입수처가 표시됩니다.'}</div></div><small>같은 보물은 한 장수만 사용할 수 있습니다. 새 보물은 전장 첫 승리와 보물 인연 외전에서 얻습니다.</small></section>`;
}
