/** Recorded CC0 samples in public/sfx (see docs/tech/sound-credits.md). Generated from the
 * selection script; each group lists its takes. Zheng takes carry their measured MIDI pitch. */
export const SAMPLE_GROUPS:Record<string,{files:string[];midi?:number[]}>={
  'swing':{files:["swing-0.mp3", "swing-1.mp3", "swing-2.mp3", "swing-3.mp3", "swing-4.mp3", "swing-5.mp3"]},
  'slash':{files:["slash-0.mp3", "slash-1.mp3", "slash-2.mp3", "slash-3.mp3", "slash-4.mp3", "slash-5.mp3"]},
  'blade':{files:["blade-0.mp3", "blade-1.mp3", "blade-2.mp3", "blade-3.mp3", "blade-4.mp3", "blade-5.mp3"]},
  'anvil':{files:["anvil-0.mp3", "anvil-1.mp3", "anvil-2.mp3"]},
  'metal-hit':{files:["metal-hit-0.mp3", "metal-hit-1.mp3", "metal-hit-2.mp3", "metal-hit-3.mp3", "metal-hit-4.mp3"]},
  'plate-hit':{files:["plate-hit-0.mp3", "plate-hit-1.mp3", "plate-hit-2.mp3", "plate-hit-3.mp3", "plate-hit-4.mp3"]},
  'punch':{files:["punch-0.mp3", "punch-1.mp3", "punch-2.mp3", "punch-3.mp3"]},
  'flesh':{files:["flesh-0.mp3", "flesh-1.mp3", "flesh-2.mp3"]},
  'evade':{files:["evade-0.mp3", "evade-1.mp3", "evade-2.mp3", "evade-3.mp3"]},
  'shield':{files:["shield-0.mp3", "shield-1.mp3", "shield-2.mp3", "shield-3.mp3", "shield-4.mp3"]},
  'draw':{files:["draw-0.mp3", "draw-1.mp3", "draw-2.mp3", "draw-3.mp3", "draw-4.mp3"]},
  'arrow-fly':{files:["arrow-fly-0.mp3", "arrow-fly-1.mp3", "arrow-fly-2.mp3", "arrow-fly-3.mp3"]},
  'arrow-thunk':{files:["arrow-thunk-0.mp3", "arrow-thunk-1.mp3", "arrow-thunk-2.mp3", "arrow-thunk-3.mp3"]},
  'latch':{files:["latch-0.mp3", "latch-1.mp3", "latch-2.mp3"]},
  'wood-crack':{files:["wood-crack-0.mp3", "wood-crack-1.mp3", "wood-crack-2.mp3", "wood-crack-3.mp3"]},
  'creak':{files:["creak-0.mp3", "creak-1.mp3", "creak-2.mp3"]},
  'rock-break':{files:["rock-break-0.mp3", "rock-break-1.mp3", "rock-break-2.mp3", "rock-break-3.mp3", "rock-break-4.mp3"]},
  'stones':{files:["stones-0.mp3", "stones-1.mp3", "stones-2.mp3", "stones-3.mp3"]},
  'wood-break':{files:["wood-break-0.mp3", "wood-break-1.mp3", "wood-break-2.mp3", "wood-break-3.mp3", "wood-break-4.mp3"]},
  'ratchet':{files:["ratchet-0.mp3", "ratchet-1.mp3"]},
  'footstep':{files:["footstep-0.mp3", "footstep-1.mp3", "footstep-2.mp3", "footstep-3.mp3", "footstep-4.mp3", "footstep-5.mp3"]},
  'chain':{files:["chain-0.mp3", "chain-1.mp3", "chain-2.mp3"]},
  'cloth':{files:["cloth-0.mp3", "cloth-1.mp3", "cloth-2.mp3", "cloth-3.mp3"]},
  'splash':{files:["splash-0.mp3", "splash-1.mp3", "splash-2.mp3", "splash-3.mp3", "splash-4.mp3", "splash-5.mp3"]},
  'water-loop':{files:["water-loop-0.mp3", "water-loop-1.mp3"]},
  'ocean':{files:["ocean-0.mp3"]},
  'fire':{files:["fire-0.mp3", "fire-1.mp3", "fire-2.mp3", "fire-3.mp3", "fire-4.mp3"]},
  'spell':{files:["spell-0.mp3", "spell-1.mp3"]},
  'boom':{files:["boom-0.mp3", "boom-1.mp3", "boom-2.mp3", "boom-3.mp3"]},
  'zap':{files:["zap-0.mp3"]},
  'hammer':{files:["hammer-0.mp3", "hammer-1.mp3", "hammer-2.mp3", "hammer-3.mp3", "hammer-4.mp3"]},
  'pain':{files:["pain-0.mp3", "pain-1.mp3", "pain-2.mp3", "pain-3.mp3"]},
  'death':{files:["death-0.mp3", "death-1.mp3", "death-2.mp3", "death-3.mp3"]},
  'grunt':{files:["grunt-0.mp3", "grunt-1.mp3", "grunt-2.mp3", "grunt-3.mp3", "grunt-4.mp3"]},
  'book':{files:["book-0.mp3", "book-1.mp3", "book-2.mp3"]},
  'click':{files:["click-0.mp3", "click-1.mp3", "click-2.mp3"]},
  'open':{files:["open-0.mp3", "open-1.mp3"]},
  'gong':{files:["gong-0.mp3", "gong-1.mp3", "gong-2.mp3"]},
  'gong-light':{files:["gong-light-0.mp3", "gong-light-1.mp3"]},
  'bass-drum':{files:["bass-drum-0.mp3", "bass-drum-1.mp3", "bass-drum-2.mp3"]},
  'frame-drum':{files:["frame-drum-0.mp3", "frame-drum-1.mp3", "frame-drum-2.mp3"]},
  'woodblock':{files:["woodblock-0.mp3", "woodblock-1.mp3", "woodblock-2.mp3"]},
  'cymbal':{files:["cymbal-0.mp3", "cymbal-1.mp3"]},
  'chime':{files:["chime-0.mp3", "chime-1.mp3", "chime-2.mp3", "chime-3.mp3", "chime-4.mp3"]},
  'bell-tree':{files:["bell-tree-0.mp3", "bell-tree-1.mp3"]},
  'handbell':{files:["handbell-0.mp3", "handbell-1.mp3", "handbell-2.mp3"]},
  'horn':{files:["horn-0.mp3", "horn-1.mp3"]},
  'zheng':{files:["zheng-0.mp3", "zheng-1.mp3", "zheng-2.mp3", "zheng-3.mp3", "zheng-4.mp3", "zheng-5.mp3", "zheng-6.mp3", "zheng-7.mp3", "zheng-8.mp3", "zheng-9.mp3", "zheng-10.mp3", "zheng-11.mp3", "zheng-12.mp3", "zheng-13.mp3", "zheng-14.mp3", "zheng-15.mp3"], midi:[47, 71.2, 70.9, 49.2, 61.4, 72.9, 51.2, 63.1, 75.1, 54.1, 65.9, 78.1, 56.1, 68, 80.2, 59.1]},
};
export const SAMPLE_ORIGINS:Record<string,string[]>={
  'swing':["cc0sounds/Micro Pack - Organic Wooshes/Classic Swish 1.mp3", "cc0sounds/Micro Pack - Organic Wooshes/Classic Swish 2.mp3", "cc0sounds/Micro Pack - Organic Wooshes/Swish 1.mp3", "cc0sounds/Micro Pack - Organic Wooshes/Swish 2.mp3", "cc0sounds/Micro Pack - Organic Wooshes/Swish 3.mp3", "cc0sounds/Micro Pack - Organic Wooshes/Swish 5.mp3"],
  'slash':["cc0sounds/Micro Pack - Organic Wooshes/Slash.mp3", "cc0sounds/kenney_rpgaudio/Audio/knifeSlice.ogg", "cc0sounds/kenney_rpgaudio/Audio/knifeSlice2.ogg", "cc0sounds/warfork-cc0/sounds/weapons/blade_strike1.ogg", "cc0sounds/warfork-cc0/sounds/weapons/blade_strike2.ogg", "cc0sounds/warfork-cc0/sounds/weapons/blade_strike3.ogg"],
  'blade':["cc0sounds/80-CC0-RPG-SFX/blade_01.ogg", "cc0sounds/80-CC0-RPG-SFX/blade_02.ogg", "cc0sounds/80-CC0-RPG-SFX/blade_03.ogg", "cc0sounds/80-CC0-RPG-SFX/metal_01.ogg", "cc0sounds/80-CC0-RPG-SFX/metal_02.ogg", "cc0sounds/80-CC0-RPG-SFX/metal_03.ogg"],
  'anvil':["VCSL/Idiophones/Struck Idiophones/Anvil/Anvil_Hit1_v2_rr1_Mid.mp3", "VCSL/Idiophones/Struck Idiophones/Anvil/Anvil_Hit2_v2_rr1_Mid.mp3", "VCSL/Idiophones/Struck Idiophones/Anvil/Anvil_Hit3_v2_rr1_Mid.mp3"],
  'metal-hit':["cc0sounds/kenney_impactsounds/Audio/impactMetal_heavy_000.ogg", "cc0sounds/kenney_impactsounds/Audio/impactMetal_heavy_001.ogg", "cc0sounds/kenney_impactsounds/Audio/impactMetal_medium_000.ogg", "cc0sounds/kenney_impactsounds/Audio/impactMetal_medium_001.ogg", "cc0sounds/kenney_impactsounds/Audio/impactMetal_medium_002.ogg"],
  'plate-hit':["cc0sounds/kenney_impactsounds/Audio/impactPlate_heavy_000.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlate_heavy_001.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlate_medium_000.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlate_medium_001.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlate_medium_002.ogg"],
  'punch':["cc0sounds/kenney_impactsounds/Audio/impactPunch_heavy_000.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPunch_heavy_001.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPunch_heavy_002.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPunch_heavy_003.ogg"],
  'flesh':["cc0sounds/warfork-cc0/sounds/weapons/blade_hitflsh1.ogg", "cc0sounds/warfork-cc0/sounds/weapons/blade_hitflsh2.ogg", "cc0sounds/warfork-cc0/sounds/weapons/blade_hitflsh3.ogg"],
  'evade':["cc0sounds/Micro Pack - Organic Wooshes/Gentle Swish.mp3", "cc0sounds/Micro Pack - Organic Wooshes/Twirl Smol 1.mp3", "cc0sounds/Micro Pack - Organic Wooshes/Twirl Smol 2.mp3", "cc0sounds/Micro Pack - Organic Wooshes/Twirl Smol 3.mp3"],
  'shield':["cc0sounds/kenney_impactsounds/Audio/impactMetal_light_000.ogg", "cc0sounds/kenney_impactsounds/Audio/impactMetal_light_001.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlank_medium_000.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlank_medium_001.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlank_medium_002.ogg"],
  'draw':["cc0sounds/Micro Pack - Kitchen Knives/Big Knife - Unsheath 1.mp3", "cc0sounds/Micro Pack - Kitchen Knives/Big Knife - Unsheath 2.mp3", "cc0sounds/kenney_rpgaudio/Audio/drawKnife1.ogg", "cc0sounds/kenney_rpgaudio/Audio/drawKnife2.ogg", "cc0sounds/kenney_rpgaudio/Audio/drawKnife3.ogg"],
  'arrow-fly':["cc0sounds/Micro Pack - Organic Wooshes/Whistle 1.mp3", "cc0sounds/Micro Pack - Organic Wooshes/Whistle 2.mp3", "cc0sounds/Micro Pack - Organic Wooshes/Whistle 3.mp3", "cc0sounds/Micro Pack - Organic Wooshes/Whistle 4.mp3"],
  'arrow-thunk':["cc0sounds/Micro Pack - Organic Wooshes/Thunk 1.mp3", "cc0sounds/Micro Pack - Organic Wooshes/Thunk 2.mp3", "cc0sounds/kenney_impactsounds/Audio/impactPlank_medium_003.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlank_medium_004.ogg"],
  'latch':["cc0sounds/kenney_rpgaudio/Audio/beltHandle1.ogg", "cc0sounds/kenney_rpgaudio/Audio/metalClick.ogg", "cc0sounds/kenney_rpgaudio/Audio/metalLatch.ogg"],
  'wood-crack':["cc0sounds/100-CC0-wood-metal-SFX/wood_cracking_01.ogg", "cc0sounds/100-CC0-wood-metal-SFX/wood_cracking_02.ogg", "cc0sounds/100-CC0-wood-metal-SFX/wood_cracking_03.ogg", "cc0sounds/100-CC0-wood-metal-SFX/wood_cracking_04.ogg"],
  'creak':["cc0sounds/kenney_rpgaudio/Audio/creak1.ogg", "cc0sounds/kenney_rpgaudio/Audio/creak2.ogg", "cc0sounds/kenney_rpgaudio/Audio/creak3.ogg"],
  'rock-break':["cc0sounds/75-cc0-breaking-falling-hit-sfx/bfh1_rock_breaking_01.ogg", "cc0sounds/75-cc0-breaking-falling-hit-sfx/bfh1_rock_breaking_02.ogg", "cc0sounds/75-cc0-breaking-falling-hit-sfx/bfh1_rock_breaking_03.ogg", "cc0sounds/75-cc0-breaking-falling-hit-sfx/bfh1_rock_falling_01.ogg", "cc0sounds/75-cc0-breaking-falling-hit-sfx/bfh1_rock_falling_02.ogg"],
  'stones':["cc0sounds/80-CC0-RPG-SFX/stones_01.ogg", "cc0sounds/80-CC0-RPG-SFX/stones_02.ogg", "cc0sounds/80-CC0-RPG-SFX/stones_03.ogg", "cc0sounds/80-CC0-RPG-SFX/stones_04.ogg"],
  'wood-break':["cc0sounds/100-CC0-wood-metal-SFX/wood_breaking_01.ogg", "cc0sounds/100-CC0-wood-metal-SFX/wood_breaking_02.ogg", "cc0sounds/100-CC0-wood-metal-SFX/wood_slam_01.ogg", "cc0sounds/75-cc0-breaking-falling-hit-sfx/bfh1_wood_breaking_01.ogg", "cc0sounds/75-cc0-breaking-falling-hit-sfx/bfh1_wood_breaking_02.ogg"],
  'ratchet':["VCSL/Idiophones/Struck Idiophones/Ratchet/Ratchet1_Slow_rr1_Mid.mp3", "VCSL/Idiophones/Struck Idiophones/Ratchet/Ratchet2_Slow_rr1_Mid.mp3"],
  'footstep':["cc0sounds/kenney_impactsounds/Audio/footstep_concrete_000.ogg", "cc0sounds/kenney_impactsounds/Audio/footstep_concrete_001.ogg", "cc0sounds/kenney_impactsounds/Audio/footstep_grass_000.ogg", "cc0sounds/kenney_impactsounds/Audio/footstep_grass_001.ogg", "cc0sounds/kenney_impactsounds/Audio/footstep_grass_002.ogg", "cc0sounds/kenney_impactsounds/Audio/footstep_grass_003.ogg"],
  'chain':["cc0sounds/80-CC0-RPG-SFX/chain_01.ogg", "cc0sounds/80-CC0-RPG-SFX/chain_02.ogg", "cc0sounds/80-CC0-RPG-SFX/chain_03.ogg"],
  'cloth':["cc0sounds/kenney_rpgaudio/Audio/cloth1.ogg", "cc0sounds/kenney_rpgaudio/Audio/cloth2.ogg", "cc0sounds/kenney_rpgaudio/Audio/cloth3.ogg", "cc0sounds/kenney_rpgaudio/Audio/cloth4.ogg"],
  'splash':["cc0sounds/40-cc0-water-splash-slime-sfx/splash_01.ogg", "cc0sounds/40-cc0-water-splash-slime-sfx/splash_02.ogg", "cc0sounds/40-cc0-water-splash-slime-sfx/splash_03.ogg", "cc0sounds/40-cc0-water-splash-slime-sfx/splash_04.ogg", "cc0sounds/40-cc0-water-splash-slime-sfx/splash_05.ogg", "cc0sounds/40-cc0-water-splash-slime-sfx/splash_06.ogg"],
  'water-loop':["cc0sounds/40-cc0-water-splash-slime-sfx/loop_water_01.ogg", "cc0sounds/40-cc0-water-splash-slime-sfx/loop_water_02.ogg"],
  'ocean':["VCSL/Membranophones/Other Membranophones/Ocean Drum/OceanDrum_Sus_1_Mid.mp3"],
  'fire':["cc0sounds/80-CC0-RPG-SFX/spell_fire_01.ogg", "cc0sounds/80-CC0-RPG-SFX/spell_fire_02.ogg", "cc0sounds/80-CC0-RPG-SFX/spell_fire_03.ogg", "cc0sounds/80-CC0-RPG-SFX/spell_fire_04.ogg", "cc0sounds/80-CC0-RPG-SFX/spell_fire_05.ogg"],
  'spell':["cc0sounds/80-CC0-RPG-SFX/spell_01.ogg", "cc0sounds/80-CC0-RPG-SFX/spell_02.ogg"],
  'boom':["cc0sounds/25-CC0-bang-sfx/cannon_01.ogg", "cc0sounds/25-CC0-bang-sfx/cannon_02.ogg", "cc0sounds/25-CC0-bang-sfx/cannon_03.ogg", "cc0sounds/warfork-cc0/sounds/weapons/gren_strong_explosion1.ogg"],
  'zap':["cc0sounds/warfork-cc0/sounds/weapons/electrobolt_hit.ogg"],
  'hammer':["cc0sounds/100-CC0-wood-metal-SFX/hammer_01.ogg", "cc0sounds/100-CC0-wood-metal-SFX/hammer_02.ogg", "cc0sounds/100-CC0-wood-metal-SFX/hammer_03.ogg", "cc0sounds/100-CC0-wood-metal-SFX/wood_hammer_01.ogg", "cc0sounds/100-CC0-wood-metal-SFX/wood_hammer_02.ogg"],
  'pain':["cc0sounds/warfork-cc0/sounds/players/male/pain100.ogg", "cc0sounds/warfork-cc0/sounds/players/male/pain25.ogg", "cc0sounds/warfork-cc0/sounds/players/male/pain50.ogg", "cc0sounds/warfork-cc0/sounds/players/male/pain75.ogg"],
  'death':["cc0sounds/80-CC0-creature-SFX/scream_01.ogg", "cc0sounds/80-CC0-creature-SFX/scream_02.ogg", "cc0sounds/warfork-cc0/sounds/players/male/death.ogg", "cc0sounds/warfork-cc0/sounds/players/male/falldeath.ogg"],
  'grunt':["cc0sounds/80-CC0-creature-SFX/grunt_01.ogg", "cc0sounds/80-CC0-creature-SFX/grunt_02.ogg", "cc0sounds/80-CC0-creature-SFX/grunt_03.ogg", "cc0sounds/80-CC0-creature-SFX/grunt_04.ogg", "cc0sounds/80-CC0-creature-SFX/grunt_05.ogg"],
  'book':["cc0sounds/kenney_rpgaudio/Audio/bookFlip1.ogg", "cc0sounds/kenney_rpgaudio/Audio/bookFlip2.ogg", "cc0sounds/kenney_rpgaudio/Audio/bookFlip3.ogg"],
  'click':["cc0sounds/kenney_interfacesounds/Audio/click_001.ogg", "cc0sounds/kenney_interfacesounds/Audio/click_002.ogg", "cc0sounds/kenney_interfacesounds/Audio/click_003.ogg"],
  'open':["cc0sounds/kenney_interfacesounds/Audio/open_001.ogg", "cc0sounds/kenney_interfacesounds/Audio/open_002.ogg"],
  'gong':["VCSL/Idiophones/Struck Idiophones/Gong 1/gong_f.mp3", "VCSL/Idiophones/Struck Idiophones/Gong 1/gong_mf.mp3", "VCSL/Idiophones/Struck Idiophones/Gong 2/hit_full1.mp3"],
  'gong-light':["VCSL/Idiophones/Struck Idiophones/Gong 2/hit_light1.mp3", "VCSL/Idiophones/Struck Idiophones/Gong 2/hit_light2.mp3"],
  'bass-drum':["VCSL/Membranophones/Struck Membranophones/Bass Drum 1/BDrumNew_hit_v5_rr1_Sum.mp3", "VCSL/Membranophones/Struck Membranophones/Bass Drum 1/BDrumNew_hit_v7_rr1_Sum.mp3", "VCSL/Membranophones/Struck Membranophones/Bass Drum 1/BDrumNew_hit_v7_rr2_Sum.mp3"],
  'frame-drum':["VCSL/Membranophones/Struck Membranophones/Frame Drum/HDrumL_Hit_v3_rr1_Sum.mp3", "VCSL/Membranophones/Struck Membranophones/Frame Drum/HDrumL_Hit_v3_rr2_Sum.mp3", "VCSL/Membranophones/Struck Membranophones/Frame Drum/HDrumS_Hit_v3_rr1_Sum.mp3"],
  'woodblock':["VCSL/Idiophones/Struck Idiophones/Woodblock/wood_click_f_rr1.mp3", "VCSL/Idiophones/Struck Idiophones/Woodblock/wood_click_f_rr2.mp3", "VCSL/Idiophones/Struck Idiophones/Woodblock/wood_click_mp.mp3"],
  'cymbal':["VCSL/Idiophones/Struck Idiophones/Clash Cymbals 1/cymbal_crash1_mf1.mp3", "VCSL/Idiophones/Struck Idiophones/Clash Cymbals 1/cymbal_crash1_short1.mp3"],
  'chime':["VCSL/Idiophones/Struck Idiophones/Hand Chimes/sus_A4_r01_main.mp3", "VCSL/Idiophones/Struck Idiophones/Hand Chimes/sus_C5_r01_main.mp3", "VCSL/Idiophones/Struck Idiophones/Hand Chimes/sus_C6_r01_main.mp3", "VCSL/Idiophones/Struck Idiophones/Hand Chimes/sus_D5_r01_main.mp3", "VCSL/Idiophones/Struck Idiophones/Hand Chimes/sus_E5_r01_main.mp3"],
  'bell-tree':["VCSL/Idiophones/Struck Idiophones/Bell Tree/Stroke/BellTree_Stroke_1_Mid.mp3", "VCSL/Idiophones/Struck Idiophones/Bell Tree/Stroke/BellTree_Stroke_3_Mid.mp3"],
  'handbell':["VCSL/Idiophones/Struck Idiophones/Hand Bells, Nepalese/HB_1.mp3", "VCSL/Idiophones/Struck Idiophones/Hand Bells, Nepalese/HB_2.mp3", "VCSL/Idiophones/Struck Idiophones/Hand Bells, Nepalese/HB_3.mp3"],
  'horn':["VCSL/Aerophones/Lip Aerophones/Didgeridoo/Didgeridoo1_Sus2_Main.mp3", "VCSL/Aerophones/Lip Aerophones/Didgeridoo/Didgeridoo1_Sus3_Main.mp3"],
  'zheng':["VCSL/Chordophones/Zithers/Dan Tranh/Normal/B1_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/B3_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/B4_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/C#2_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/C#3_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/C#4_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/D#2_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/D#3_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/D#4_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/F#2_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/F#3_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/F#4_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/G#2_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/G#3_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/G#4_mf_1.mp3", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/b2_mf_1.mp3"],
};

/** One layer of a sound: a recorded group, or `synth` to keep the synthesized recipe. */
export interface SampleLayer {group?:string;synth?:boolean;gain?:number;delay?:number;rate?:number}
const L=(group:string,gain=1,delay=0,rate=1):SampleLayer=>({group,gain,delay,rate});
const SYNTH=(gain=1,delay=0):SampleLayer=>({synth:true,gain,delay});
/**
 * How each sound name is built from recordings. Names not listed (neigh) stay fully
 * synthesized because no CC0 recording close enough was available. Where no direct
 * recording exists the sound is built the way foley artists do it: hooves from a
 * low-pitched wood block and footfalls in the three-beat gallop rhythm, a cheer from
 * several pitched-up shouts over the synthesized crowd.
 */
export const SAMPLE_LAYERS:Record<string,SampleLayer[]>={
  swing:[L('swing')],
  gallop:[...[0,.085,.2,.39,.475,.59].flatMap((t,i)=>[L('woodblock',i%3===2?.55:.4,t,.52+(i%3)*.04),L('footstep',i%3===2?.7:.5,t+.004,.62)]),L('stones',.25,.05,.8)],
  cheer:[SYNTH(.6),L('grunt',.45,0,1.25),L('grunt',.4,.06,1.4),L('grunt',.4,.12,1.15),L('pain',.3,.18,1.45),L('grunt',.35,.24,1.3)],
  cast:[L('spell',.7),SYNTH(.55),L('cloth',.45,.02)],
  clash:[L('blade'),L('anvil',.35,.005)],
  stab:[L('slash',.8),L('flesh',.9,.04)],
  'armor-hit':[L('plate-hit'),L('punch',.6)],
  'heavy-hit':[L('punch'),L('plate-hit',.8,.01),L('metal-hit',.45,.02)],
  evade:[L('evade')],
  guard:[L('shield')],
  'bow-release':[SYNTH(.45),L('arrow-fly',.9,.03)],
  'crossbow-release':[L('latch',.8),L('arrow-fly',.8,.06)],
  'arrow-hit':[L('arrow-thunk')],
  'arrow-volley':[L('arrow-fly',.7),L('arrow-fly',.6,.06,1.08),L('arrow-fly',.6,.12,.93),L('arrow-thunk',.8,.45),L('arrow-thunk',.7,.52)],
  'catapult-launch':[L('wood-crack'),L('creak',.6),L('swing',.7,.15,.65)],
  'boulder-hit':[L('rock-break'),L('boom',.5,0,1.3),L('stones',.6,.1)],
  'ram-hit':[L('wood-break'),L('bass-drum',.9),L('metal-hit',.4,.01)],
  wheels:[L('ratchet',.7),L('creak',.5,.1)],
  march:[L('footstep',.8),L('footstep',.7,.17),L('footstep',.75,.34),L('chain',.25,.05)],
  robe:[L('cloth')],
  oars:[L('splash',.6),L('creak',.4,.1),L('splash',.45,.5,1.1)],
  shout:[L('grunt')],
  pain:[L('pain')],
  death:[L('death')],
  'battle-cry':[SYNTH(.5),L('grunt',.6,0,.85),L('grunt',.55,.08,1.1),L('pain',.5,.15,.9),L('grunt',.5,.22,.95),L('pain',.45,.3,1.15),L('grunt',.45,.38,.8)],
  fire:[L('fire')],
  wind:[SYNTH(),L('swing',.5,.2,.6)],
  water:[L('splash'),L('water-loop',.7,.1),L('ocean',.5,.2)],
  thunder:[L('zap',.5),L('boom',1,.05,.8),SYNTH(.5,.1)],
  earth:[L('stones'),L('rock-break',.6,.05),L('chain',.6,.2)],
  confuse:[L('spell'),SYNTH(.45)],
  heal:[L('bell-tree',.8),L('chime',.6,.1),L('chime',.5,.25)],
  buff:[L('gong-light',.8),L('frame-drum',.7),L('chime',.4,.2)],
  repair:[L('hammer'),L('hammer',.9,.28),L('hammer',.85,.56)],
  crumble:[L('rock-break'),L('wood-break',.7,.1),L('stones',.6,.3)],
  gong:[L('gong')],
  'war-drum':[L('bass-drum'),L('bass-drum',.8,.32),L('bass-drum',1,.62)],
  'enemy-drum':[L('bass-drum',1,0,.8),L('bass-drum',.9,.5,.8)],
  horn:[SYNTH(.6),L('horn',.8)],
  fanfare:[SYNTH(),L('cymbal',.6,.75),L('gong',.6,.75)],
  lament:[SYNTH(),L('gong-light',.5,1.4,.85)],
  'ui-click':[L('click',.8)],
  'ui-open':[L('open',.7)],
  page:[L('book',.8)],
  taiko:[L('bass-drum')],
  'taiko-small':[L('frame-drum')],
  woodblock:[L('woodblock')],
  'temple-bell':[L('handbell')],
};

/** MP3 encoders pad the start with silence (~35 ms). Hits must land on the frame, so
 * the silent lead-in is skipped, keeping 2 ms so the attack is not clipped. */
export function leadIn(data:Float32Array,rate:number,threshold=.003){
  const limit=Math.min(data.length,Math.round(rate*.12));let i=0;
  while(i<limit&&Math.abs(data[i]!)<threshold)i++;
  return i>=limit?0:Math.max(0,i-Math.round(rate*.002));
}
