import type {Treasure,GearSlot} from './progression.ts';
// Four discoveries per side story. Stable IDs preserve equipment saves.
const entries:Array<[string,string,GearSlot,number,number,string]>=[
 ['doubleSwords','자웅일대검','weapon',3,1,'Q01'],['ancientBlade','고정도','weapon',3,4,'Q01'],['leatherArmor','피갑','armor',1,15,'Q01'],['warDrum','진군고','accessory',1,14,'Q01'],
 ['ironSpear','철척사모','weapon',2,9,'Q02'],['flyingBlade','비도','weapon',2,7,'Q02'],['chainArmor','쇄자갑','armor',2,0,'Q02'],['militarySeal','장군인','accessory',2,14,'Q02'],
 ['phoenixSpear','봉취도','weapon',3,9,'Q03'],['crescentBlade','월아극','weapon',3,10,'Q03'],['scaleArmor','어린갑','armor',2,15,'Q03'],['swiftSaddle','비운안','accessory',2,5,'Q03'],
 ['ironBow','철태궁','weapon',3,11,'Q04'],['repeatingCrossbow','원융노','weapon',3,11,'Q04'],['rattanArmor','등갑','armor',3,15,'Q04'],['sunzi','손자병법서','accessory',3,6,'Q04'],
 ['threePointBlade','삼첨도','weapon',3,8,'Q05'],['steelWhip','강편','weapon',2,9,'Q05'],['brightArmor','명광개','armor',3,0,'Q05'],['sixTeachings','육도','accessory',3,3,'Q05'],
 ['longbow','양유궁','weapon',3,11,'Q06'],['ironAxe','개산부','weapon',2,10,'Q06'],['blackArmor','현철갑','armor',3,15,'Q06'],['threeStrategies','삼략','accessory',3,2,'Q06'],
 ['dragonSpear','용담창','weapon',4,9,'Q07'],['twinHalberds','쌍철극','weapon',3,10,'Q07'],['tigerArmor','호위갑','armor',3,0,'Q07'],['shadowHorse','절영','accessory',4,12,'Q07'],
 ['goldHammer','유금추','weapon',3,10,'Q08'],['moonSword','월광검','weapon',3,7,'Q08'],['craneRobe','학창','armor',3,0,'Q08'],['yellowHorse','조황비전','accessory',4,5,'Q08'],
 ['jadeSword','백옥검','weapon',4,1,'Q09'],['tigerSpear','호두창','weapon',3,9,'Q09'],['cloudRobe','운금포','armor',3,0,'Q09'],['qingshu','청낭서','accessory',4,3,'Q09'],
 ['sevenStarFlag','칠성기','accessory',4,13,'Q10'],['formationScroll','팔진도','accessory',4,2,'Q10'],['dragonArmor','용린갑옷','armor',4,15,'Q10'],['goldArmor','황금갑옷','armor',4,0,'Q10'],
 ['springAutumn','춘추좌씨전','accessory',4,6,'Q11'],['jadePendant','백옥환','accessory',3,14,'Q11'],['tigerTally','호부','accessory',4,14,'Q11'],['strategistRobe','군사포','armor',4,0,'Q11'],
];
export const extraTreasures:Treasure[]=entries.map(([id,name,slot,grade,icon,quest],i)=>{
 const bonus:Treasure['bonus']=slot==='weapon'?{attack:2+grade, ...(i%2?{agility:2}:{maxHp:4})}:slot==='armor'?{defense:grade+1,maxHp:grade*3}:i%3===0?{maxMp:grade*2,intellect:grade}:i%3===1?{spirit:grade+1,agility:grade}:{maxHp:grade*3,agility:grade};
 const names:Record<string,string>={attack:'공격',defense:'방어',maxHp:'최대 체력',maxMp:'최대 MP',intellect:'지력',spirit:'정신',agility:'민첩'};
 return {id,name,slot,grade,icon,quest,stage:quest,glyph:slot==='weapon'?'무':slot==='armor'?'갑':'보',bonus,effect:Object.entries(bonus).map(([k,v])=>names[k]+' +'+v).join(' · '),description:['흩어진 병장기를 되찾아 장인의 손에서 되살린 보물.','험한 길을 함께 넘은 이들이 신뢰의 증표로 건넨 보물.','전란 속에서 지켜 낸 기록과 기술이 담긴 보물.'][i%3]!};
});

/**
 * 연무장(훈련) 첫 승리에 얻는 새 형태의 보물: 방패·투구·암기·거울·호로·비녀·신발·영패 등.
 * 그림 판(treasures-v2.webp) 밖이라 그림은 public/treasures/<id>.webp 낱장을 쓴다(treasure-art.ts).
 */
const trainingEntries:Array<[string,string,GearSlot,number,string,Treasure['bonus'],string]>=[
 ['rattanShield','등패','armor',1,'T01',{defense:2,maxHp:4},'등나무를 엮어 만든 가벼운 방패. 화살을 튕겨 내는 데 쓴다.'],
 ['hujia','호가십팔박','accessory',1,'T01',{spirit:2,maxMp:2},'흉노 땅에서 돌아온 채염이 지었다는 호가의 노래.'],
 ['meteorHammer','유성추','weapon',2,'T02',{attack:4,agility:2},'쇠사슬 끝에 쇠망치를 단 암기. 갑옷 위로 내리친다.'],
 ['phoenixHelm','봉시투구','armor',2,'T02',{defense:3,maxHp:6},'봉황의 깃을 꽂은 장수의 투구.'],
 ['hookSpear','구겸창','weapon',3,'T03',{attack:5,maxHp:4},'갈고리 낫을 단 창. 말의 다리를 걸어 기병을 넘어뜨린다.'],
 ['baguaMirror','팔괘경','accessory',3,'T03',{spirit:4,intellect:2},'뒷면에 팔괘를 새긴 청동 거울. 요사스러운 술수를 되비춘다.'],
 ['purpleGourd','자금호로','accessory',3,'T07',{maxMp:6,maxHp:6},'붉은 금빛 호리병. 도사가 단약을 담아 다녔다.'],
 ['bearCloak','흑웅피 망토','armor',2,'T07',{defense:2,maxHp:9},'검은 곰 가죽으로 지은 망토. 강바람과 칼끝을 함께 막는다.'],
 ['phoenixHairpin','봉황비녀','accessory',3,'T04',{agility:3,spirit:2},'봉황을 새긴 금비녀. 지닌 이를 날래게 한다는 말이 있다.'],
 ['swiftBoots','신행화','accessory',3,'T04',{agility:4,maxHp:3},'먼 길을 하루에 간다는 신행태보의 가죽신.'],
 ['zhanmaDao','참마도','weapon',4,'T05',{attack:6,maxHp:6},'말과 사람을 한 번에 벤다는 긴 자루의 큰 칼.'],
 ['tigerShield','호두패','armor',4,'T05',{defense:5,maxHp:10},'범의 머리를 새긴 큰 방패. 정면 교전에서 무너지지 않는다.'],
 ['lionHelm','사자투구','armor',4,'T06',{defense:4,maxHp:12},'금빛 사자 머리 투구. 장수의 위용을 드러낸다.'],
 ['tortoiseToken','현무영패','accessory',4,'T06',{defense:2,spirit:4},'북방 현무를 새긴 영패. 진을 지키는 장수에게 내린다.'],
];
/**
 * 반복 퀘스트(보물 사냥 R01~R05)의 보물 꾸러미와 도전 퀘스트(C01~C10) 돌파 보물.
 * 보물 사냥은 이길 때마다 꾸러미에서 아직 없는 보물 하나, 도전은 단계를 처음 넘을 때 받는다(5·10단계와 사신보옥이 붙은 6~9단계는 둘).
 */
const questEntries:Array<[string,string,GearSlot,number,string,Treasure['bonus'],string]>=[
 ['bronzeSword','백리검','weapon',1,'R01',{attack:3,agility:1},'손권이 지녔다는 여섯 명검(백홍·자전·벽사·유성·청명·백리) 가운데 하나.'],
 ['hornBowSmall','이광궁','weapon',2,'R01',{attack:4,agility:2},'한의 비장군 이광의 활. 바위에 화살촉이 박혔다는 고사가 전한다.'],
 ['hideShield','피패','armor',1,'R01',{defense:2,maxHp:5},'소가죽을 씌운 나무 방패. 칼날이 미끄러진다.'],
 ['strawCape','도롱이','armor',1,'R01',{defense:1,maxHp:6,agility:1},'짚으로 엮은 비옷. 화살이 엉켜 힘을 잃는다.'],
 ['copperBell','감녕의 방울','accessory',1,'R01',{spirit:2,maxMp:2},'감녕은 젊어서 방울을 차고 다녀, 방울 소리만 들려도 사람들이 그가 온 줄 알았다.'],
 ['travelPouch','금낭','accessory',2,'R01',{maxHp:6,agility:1},'위급할 때 열어 보라며 계책을 넣어 준 비단 주머니.'],
 ['ringBlade','환수도','weapon',2,'R02',{attack:5,maxHp:3},'자루 끝에 고리를 단 한나라 군도.'],
 ['ironRod','철곤','weapon',2,'R02',{attack:5,defense:1},'쇠를 씌운 몽둥이. 갑옷 위로 뼈를 울린다.'],
 ['lamellarVest','양당개','armor',2,'R02',{defense:3,maxHp:6},'가슴과 등을 두 장의 판으로 막는 갑옷. 조식의 상소에 하사품으로 이름이 오른다.'],
 ['wolfHelm','낭두 투구','armor',2,'R02',{defense:3,maxHp:4,spirit:1},'이리 머리 장식을 단 투구. 요술에 흔들리지 않는다.'],
 ['bambooSlips','오자','accessory',2,'R02',{intellect:3,maxMp:3},'전국 시대 오기가 남긴 병법. 손자와 나란히 병가의 으뜸으로 꼽힌다.'],
 ['ponyBridle','대완마','accessory',3,'R02',{agility:3,maxHp:4},'서역 대완에서 난다는 한혈마. 하루에 천 리를 달린다.'],
 ['snakeBlade','청명검','weapon',3,'R03',{attack:6,agility:2},'손권의 여섯 명검 가운데 하나. 푸른 하늘빛이 감도는 칼날.'],
 ['armorPiercer','파갑추','weapon',3,'R03',{attack:6,maxHp:4},'끝이 뾰족한 쇠망치. 갑옷을 뚫으려고 만들었다.'],
 ['boltQuiver','노전통','weapon',3,'R03',{attack:5,agility:3},'짧은 쇠뇌 살을 가득 담은 통과 손쇠뇌.'],
 ['mountainArmor','산문갑','armor',3,'R03',{defense:4,maxHp:9},'산(山) 자 무늬로 미늘을 맞춘 갑옷.'],
 ['fireproofRobe','화완포','armor',3,'R03',{defense:3,maxHp:6,spirit:2},'불에 넣으면 때만 타고 깨끗해진다는 옷감.'],
 ['beaconToken','봉화 영전','accessory',3,'R03',{spirit:3,defense:1},'봉화대 수장이 차는 화살 모양 영패.'],
 ['wuhuanBow','오환 각궁','weapon',4,'R04',{attack:7,agility:3},'북방 기마민의 큰 각궁. 달리며 쏘아도 곧게 날아간다.'],
 ['cavalrySaber','기병 환도','weapon',3,'R04',{attack:6,agility:2,maxHp:3},'말 위에서 휘두르기 좋게 휜 칼.'],
 ['feltArmor','모전갑','armor',3,'R04',{defense:4,maxHp:10},'두껍게 누빈 양털 갑옷. 화살이 박혀도 들어오지 않는다.'],
 ['horseBarding','마개','armor',4,'R04',{defense:5,maxHp:10},'말에 입히는 쇠갑옷. 조식이 선제에게 받은 마개를 바치겠다고 상소했다.'],
 ['eagleFeather','해동청 깃','accessory',4,'R04',{agility:4,spirit:2},'북방 매의 깃을 꽂은 장식. 몸놀림이 가벼워진다.'],
 ['nomadSteed','오환마','accessory',4,'R04',{agility:4,maxHp:6},'오환의 땅에서 난 준마. 조조가 백랑산에서 오환을 꺾고 얻었다.'],
 ['poisonDarts','독침 통','weapon',4,'R05',{attack:7,agility:4},'남만 사냥꾼의 대롱과 독침.'],
 ['tuskSpear','상아 창','weapon',4,'R05',{attack:8,maxHp:6},'코끼리 상아로 날을 세운 창.'],
 ['rattanHelm','등나무 투구','armor',4,'R05',{defense:5,maxHp:8},'기름 먹인 등나무로 짠 투구. 가볍고 단단하다.'],
 ['shuBrocade','촉금 전포','armor',4,'R05',{defense:5,maxHp:12,spirit:2},'촉의 비단으로 지은 전포. 피와 먼지가 스미지 않는다.'],
 ['bronzeDrum','제갈고','accessory',4,'R05',{spirit:3,maxHp:8},'남중의 청동 북. 남정 때 제갈량이 남겼다 하여 제갈고라 불린다.'],
 ['spiritBead','야명주','accessory',4,'R05',{spirit:5,maxMp:6},'밤에도 스스로 빛난다는 구슬.'],
 // 삼국지14 명품(名品)에서 가져온 보물: 보물 사냥 꾸러미에 더한다.
 ['simaFa','사마법','accessory',3,'R03',{defense:2,intellect:2,maxMp:3},'춘추의 사마 양저가 남긴 병법. 군의 예법과 상벌을 바로 세운다.'],
 ['weiLiaozi','울료자','accessory',2,'R01',{defense:2,maxMp:2},'전국 시대 울료가 지은 병서. 엄한 군령으로 진을 무너지지 않게 한다.'],
 ['shiji','사기','accessory',3,'R02',{intellect:3,spirit:2},'사마천이 황제부터 한 무제까지를 적은 역사서. 흥망의 까닭을 읽는다.'],
 ['hanfeizi','한비자','accessory',3,'R03',{intellect:3,maxMp:4},'한비가 법·술·세를 풀어낸 책. 조조와 제갈량 모두 곁에 두었다.'],
 ['guanzi','관자','accessory',3,'R03',{spirit:3,maxHp:5},'제 환공을 패자로 만든 관중의 글. 창고가 차야 예절을 안다고 했다.'],
 ['shangjunshu','상군서','accessory',3,'R03',{spirit:2,defense:2},'상앙이 진의 변법을 적은 책. 농사와 전쟁으로 나라를 일으킨다.'],
 ['yanziChunqiu','안자춘추','accessory',2,'R01',{spirit:2,maxMp:3},'제의 재상 안영의 언행을 모은 책. 두 복숭아로 세 장사를 꺾은 고사가 실려 있다.'],
 ['yinfu','주서음부','accessory',3,'R03',{intellect:4,agility:2},'소진이 밤새 읽고 합종을 이루었다는 태공의 비서.'],
 ['siminYueling','사민월령','accessory',1,'R01',{maxHp:6,spirit:1},'후한 최식이 달마다 할 농사와 살림을 적은 책. 군량을 아끼는 법이 담겼다.'],
 ['yantielun','염철론','accessory',2,'R02',{defense:2,maxHp:4},'소금과 쇠를 나라가 팔 것인가를 두고 벌인 조정의 논쟁을 엮은 책.'],
 ['laozi','노자','accessory',4,'R05',{intellect:5,maxMp:8,spirit:2},'오천 자로 도와 덕을 말한 책. 부드러운 것이 굳센 것을 이긴다.'],
 ['zhuangzi','장자','accessory',3,'R04',{intellect:3,spirit:3},'붕새와 나비 꿈의 우화로 얽매임에서 벗어나는 길을 말한 책.'],
 ['lunyu','논어','accessory',3,'R04',{spirit:3,maxMp:4,intellect:2},'공자와 제자들의 문답. 장수가 사람을 아끼는 마음을 배운다.'],
 ['shijing','시경','accessory',3,'R04',{spirit:3,maxHp:5},'주나라부터 전해진 노래 삼백 편. 출정하는 병사의 노래도 실려 있다.'],
 ['shujing','서경','accessory',2,'R02',{intellect:2,maxMp:3},'요순에서 주까지 임금과 신하의 말을 모은 책.'],
 ['yijing','역경','accessory',2,'R02',{intellect:3,spirit:1},'괘와 효로 변화의 이치를 읽는 책. 진법의 바탕이 된다.'],
 ['liji','예기','accessory',2,'R01',{spirit:2,defense:1},'예의 뜻과 제도를 적은 책. 군례로 대오를 가지런히 한다.'],
 ['taipingYaoshu','태평요술서','accessory',4,'R05',{intellect:5,maxMp:10},'남화노선이 장각에게 주었다는 비서. 바람을 부르고 비를 내린다.'],
 ['shanhaijing','산해경','accessory',4,'R05',{intellect:4,spirit:4,maxMp:6},'산과 바다의 기이한 짐승과 신령을 적은 책. 요사스러운 것을 미리 안다.'],
 ['xishuMap','서촉지형도','accessory',4,'R05',{agility:4,intellect:3},'장송이 유비에게 바친 촉의 지도. 험한 길과 관문이 낱낱이 그려져 있다.'],
 ['guoxiaMa','과하마','accessory',2,'R02',{agility:3,maxHp:3},'과일나무 아래로도 지나간다는 작은 말. 산길에서 지치지 않는다.'],
 ['liangzhouMa','양주마','accessory',3,'R04',{agility:4,maxHp:4},'서량 땅에서 난 굳센 말. 마등과 마초의 기병이 탔다.'],
 ['baihu','백곡','accessory',3,'R04',{agility:4,maxHp:5},'고니처럼 흰 준마. 조조가 아끼던 말 가운데 하나다.'],
 ['fourWheelCart','사륜차','accessory',3,'R05',{intellect:3,maxMp:4,defense:1},'제갈량이 타고 군을 지휘했다는 네 바퀴 수레.'],
 ['zhansheSword','참사검','weapon',4,'R05',{attack:9,maxHp:6},'한 고조 유방이 망탕산에서 흰 뱀을 베었다는 칼. 한 황실의 보검이다.'],
 ['baipiDao','백벽도','weapon',2,'R01',{attack:4,agility:1},'조조가 백 번 담금질해 만들게 한 다섯 자루의 칼.'],
 ['initiateBadge','초입패','accessory',2,'C01',{attack:2,defense:2},'도전의 첫 문을 넘은 이에게 주는 나무패.'],
 ['sharpSpearhead','예창두','weapon',3,'C02',{attack:6},'숲속 대장간에서 갈아 낸 날카로운 창끝.'],
 ['riverShield','강패','armor',3,'C03',{defense:4,maxHp:8},'다리를 지키던 병사의 큰 방패. 화살 자국이 빽빽하다.'],
 ['summitBanner','등봉기','accessory',3,'C04',{spirit:3,agility:3},'산 정상에 꽂던 깃발. 멀리서도 보인다.'],
 ['gatekeeperHalberd','수문장 방천극','weapon',4,'C05',{attack:9,maxHp:8},'군수고 수문장이 들던 방천극. 5단계 수문장을 꺾은 증표.'],
 ['gatekeeperArmor','흑광개','armor',4,'C05',{defense:6,maxHp:14},'검게 빛나는 판갑. 조식의 상소에 명광개와 함께 이름이 오른다. 5단계 수문장을 꺾은 증표.'],
 ['courtSeal','한수정후 인','accessory',4,'C06',{intellect:4,spirit:3},'백마에서 안량을 벤 공으로 관우가 받은 한수정후의 인수.'],
 ['cliffSandals','잔도 짚신','accessory',4,'C07',{agility:5,maxHp:5},'벼랑길을 걷던 짐꾼의 짚신. 어떤 길도 미끄러지지 않는다.'],
 ['fordHorse','백마','accessory',4,'C08',{agility:4,maxHp:8},'공손찬의 백마의종이 타던 흰 말. 오랑캐가 백마장사라 부르며 두려워했다.'],
 ['hundredPaceBow','백보 신궁','weapon',4,'C09',{attack:9,agility:3},'백 걸음 밖의 버들잎을 맞혔다는 활.'],
 ['peerlessSword','백홍검','weapon',4,'C10',{attack:11,agility:3,maxHp:6},'손권의 여섯 명검 가운데 으뜸. 칼을 뽑으면 흰 무지개가 선다 했다. 도전 10단계를 모두 넘은 증표.'],
 ['overlordArmor','패왕갑','armor',4,'C10',{defense:8,maxHp:18},'천하를 다투던 패왕의 갑옷. 마지막 수문장을 꺾은 증표.'],
 // 조조전 보물 도감에서 가져온 보물: 보물 사냥 꾸러미(R02~R05)와 도전 6~9단계(사신보옥)에 더한다.
 ['ironHelm','철투구','armor',2,'R02',{defense:3,maxHp:5},'쇠를 두들겨 만든 병사의 투구. 머리 위로 떨어지는 칼을 받아 낸다.'],
 ['beanBag','콩주머니','accessory',2,'R02',{maxHp:8,spirit:1},'말먹이 콩을 담아 허리에 차는 주머니. 행군이 길어도 지치지 않는다.'],
 ['twinWhips','쌍편','weapon',3,'R03',{attack:6,maxHp:4},'양손에 하나씩 쥐는 쇠채찍. 마디진 쇠가 갑옷 위로 뼈를 울린다.'],
 ['plantainFan','파초선','accessory',3,'R03',{intellect:4,maxMp:4},'커다란 파초 잎으로 만든 부채. 한 번 부치면 큰바람이 인다고 한다.'],
 ['mirrorArmor','거울갑옷','armor',3,'R03',{defense:4,maxHp:6,spirit:2},'가슴과 등에 둥근 동경을 단 갑옷. 햇빛을 되쏘아 적의 눈을 어지럽힌다.'],
 ['dragonGi','비룡도복','armor',3,'R03',{defense:2,maxHp:6,agility:3},'날아오르는 용을 수놓은 무도가의 옷. 몸놀림을 가볍게 한다.'],
 ['silverShield','백은방패','armor',3,'R03',{defense:5,maxHp:6},'은으로 테를 두른 방패. 정면에서 오는 칼과 창을 흘려 낸다.'],
 ['lubuBow','여포궁','weapon',4,'R04',{attack:8,agility:2},'원문에서 화살 한 대로 화극의 곁가지를 맞혀 싸움을 말렸다는 여포의 활.'],
 ['linkedArmor','연환갑옷','armor',3,'R04',{defense:5,maxHp:8},'쇠고리를 촘촘히 이어 엮은 갑옷. 칼날이 미끄러져 들어오지 못한다.'],
 ['windGodShield','풍신방패','armor',4,'R04',{defense:6,maxHp:8},'바람신을 새긴 큰 방패. 쏟아지는 화살을 바람처럼 흘려 보낸다.'],
 ['noFeatherDart','몰우전','weapon',3,'R04',{attack:5,agility:3},'깃 없는 화살이라는 뜻의 돌팔매. 던지는 족족 장수의 얼굴을 맞힌다.'],
 ['goldFireCannon','금화관포','weapon',4,'R05',{attack:8,maxHp:4},'불붙인 쇠단지를 쏘아 올리는 포. 성벽 너머까지 불길을 퍼뜨린다.'],
 ['fiveFireFan','오화신염선','accessory',4,'R05',{intellect:5,maxMp:8},'다섯 빛깔 불꽃을 수놓은 부채. 부치면 불길이 일어난다는 남방의 보물.'],
 ['sageSword','성자보검','weapon',4,'R05',{attack:7,intellect:3},'성인이 지녔다는 보검. 요사스러운 술수를 벤다.'],
 ['darkRobe','칠흑도복','armor',4,'R05',{defense:3,maxHp:8,maxMp:6},'칠흑빛 도사의 옷. 술법의 기운을 품어 책략을 받아 낸다.'],
 ['phoenixRobe','봉황깃옷','armor',4,'R05',{defense:4,maxHp:12,spirit:3},'봉황의 깃으로 지었다는 옷. 입은 이의 상처를 아물게 한다.'],
 ['windWheel','바람바퀴','accessory',4,'R05',{agility:4,maxHp:4},'바람처럼 구른다는 수레바퀴. 수레와 포차를 험한 길에서도 굴린다.'],
 ['zhugeTurban','제갈건','accessory',4,'R05',{intellect:4,maxMp:6},'제갈량이 즐겨 썼다는 비단 두건. 군막에서 계책을 다듬는다.'],
 ['azureJewel','청룡보옥','accessory',4,'C06',{attack:3,agility:3},'동방을 지키는 청룡의 보옥. 사신보옥 넷 가운데 하나.'],
 ['vermilionJewel','주작보옥','accessory',4,'C07',{intellect:3,maxMp:6},'남방을 지키는 주작의 보옥. 사신보옥 넷 가운데 하나.'],
 ['blackTortoiseJewel','현무보옥','accessory',4,'C08',{defense:3,maxHp:10},'북방을 지키는 현무의 보옥. 사신보옥 넷 가운데 하나.'],
 ['whiteTigerJewel','백호보옥','accessory',4,'C09',{agility:4,maxHp:6},'서방을 지키는 백호의 보옥. 사신보옥 넷 가운데 하나.'],
];
const STAT_KO:Record<string,string>={attack:'공격',defense:'방어',maxHp:'최대 체력',maxMp:'최대 MP',intellect:'지력',spirit:'정신',agility:'민첩'};
export const trainingTreasures:Treasure[]=trainingEntries.map(([id,name,slot,grade,quest,bonus,description])=>({id,name,slot,grade,quest,stage:quest,glyph:name.slice(0,1),bonus,description,
 effect:Object.entries(bonus).map(([k,v])=>STAT_KO[k]+' +'+v).join(' · ')}));
export const questTreasures:Treasure[]=questEntries.map(([id,name,slot,grade,quest,bonus,description])=>({id,name,slot,grade,quest,stage:quest,glyph:name.slice(0,1),bonus,description,
 effect:Object.entries(bonus).map(([k,v])=>STAT_KO[k]+' +'+v).join(' · ')}));
